"""add reminder task ids to booking

Revision ID: c8717ec76940
Revises: 0cb5d6658e52
Create Date: 2025-12-25 06:58:20.492297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8717ec76940'
down_revision: Union[str, Sequence[str], None] = '0cb5d6658e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('reminder_24h_task_id', sa.String(length=50), nullable=True))
    op.add_column('bookings', sa.Column('reminder_2h_task_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'reminder_2h_task_id')
    op.drop_column('bookings', 'reminder_24h_task_id')
    # ### end Alembic commands ###
